version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9090:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./src:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: <Yourpassworddatabase>
        MYSQL_DATABASE: <Yourdatabase>
    ports:
        - "127.0.0.1:3310:3306"

  phpmyadmin:
   image: phpmyadmin/phpmyadmin:4.8
   links:
     - database:database
   ports:
     - 9091:80
   environment:
     PMA_HOST: database
     MYSQL_USERNAME: root
     MYSQL_ROOT_PASSWORD: <Yourpassworddatabase>
   depends_on:
     - database
